mysql:
  host: localhost
  port: 3306
  user: root
  password: 123456
  database: goblog
  charset: utf8mb4

session:
  key: asdfghjkl

redis:
  address: 101.201.51.40:6379
  password: 123456
  DB: 1
  poolSize: 30
  minIdleConns: 30